FROM php:8-cli-buster

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main' > /etc/apt/sources.list.d/pgdg.list ;\
    apt-get install -y gnupg ;\
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc 2> /dev/null | apt-key add - ;\
    apt-get update ;\
    apt-get remove -y --autoremove gnupg ;\
    apt-get install libpq-dev libpq5 ;\
    /usr/local/bin/docker-php-ext-install pgsql pdo_pgsql

